[project]
name = "py_four_in_a_row"
version = "0.1.0"
description = "py_four_in_a_row: A Python implementation of the classic Four in a Row game."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pytest>=8.4.2",
    "pytest-coverage>=0.0",
]
